//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Drawing;
using System.Linq;
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.ExpressApp.Utils;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using FDIT.Core.Regionales;
using FDIT.Core.Seguridad;
using FDIT.Core.Sistema;

namespace FDIT.Core.Personas
{

    [Persistent("personas.vPersona")]
    [DefaultClassOptions]
    [ModelDefault("AllowEdit", "false")]
    public partial class AgendaPersonas : XPCustomObject
    {
        int fOID;

        [Key]
        public int OID
        {
            get { return fOID; }
            set { SetPropertyValue<int>("OID", ref fOID, value); }
        }
        int fGrupo;
        public int Grupo
        {
            get { return fGrupo; }
            set { SetPropertyValue<int>("Grupo", ref fGrupo, value); }
        }
        int fTipo;
        public int Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<int>("Tipo", ref fTipo, value); }
        }
        string fTratamiento;
        [Size(20)]
        public string Tratamiento
        {
            get { return fTratamiento; }
            set { SetPropertyValue<string>("Tratamiento", ref fTratamiento, value); }
        }
        string fApellidosPaterno;
        public string ApellidosPaterno
        {
            get { return fApellidosPaterno; }
            set { SetPropertyValue<string>("ApellidosPaterno", ref fApellidosPaterno, value); }
        }
        string fApellidosMaterno;
        public string ApellidosMaterno
        {
            get { return fApellidosMaterno; }
            set { SetPropertyValue<string>("ApellidosMaterno", ref fApellidosMaterno, value); }
        }
        string fNombrePila;
        public string NombrePila
        {
            get { return fNombrePila; }
            set { SetPropertyValue<string>("NombrePila", ref fNombrePila, value); }
        }
        string fSegundoNombre;
        public string SegundoNombre
        {
            get { return fSegundoNombre; }
            set { SetPropertyValue<string>("SegundoNombre", ref fSegundoNombre, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>("Nombre", ref fNombre, value); }
        }
        string fNombreFantasia;
        public string NombreFantasia
        {
            get { return fNombreFantasia; }
            set { SetPropertyValue<string>("NombreFantasia", ref fNombreFantasia, value); }
        }
        string fNombreCompletoAlias;
        public string NombreCompletoAlias
        {
            get { return fNombreCompletoAlias; }
            set { SetPropertyValue<string>("NombreCompletoAlias", ref fNombreCompletoAlias, value); }
        }
        DateTime fNacimientoFecha;
        public DateTime NacimientoFecha
        {
            get { return fNacimientoFecha; }
            set { SetPropertyValue<DateTime>("NacimientoFecha", ref fNacimientoFecha, value); }
        }
        DateTime fAniversarioFecha;
        public DateTime AniversarioFecha
        {
            get { return fAniversarioFecha; }
            set { SetPropertyValue<DateTime>("AniversarioFecha", ref fAniversarioFecha, value); }
        }
        int fEdad;
        public int Edad
        {
            get { return fEdad; }
            set { SetPropertyValue<int>("Edad", ref fEdad, value); }
        }
        Pais fNacimientoPais;
        public Pais NacimientoPais
        {
            get { return fNacimientoPais; }
            set { SetPropertyValue<Pais>("NacimientoPais", ref fNacimientoPais, value); }
        }
        int fSexo;
        public int Sexo
        {
            get { return fSexo; }
            set { SetPropertyValue<int>("Sexo", ref fSexo, value); }
        }
        DateTime fFallecimientoFecha;
        public DateTime FallecimientoFecha
        {
            get { return fFallecimientoFecha; }
            set { SetPropertyValue<DateTime>("FallecimientoFecha", ref fFallecimientoFecha, value); }
        }
        int fFallecimientoPais;
        public int FallecimientoPais
        {
            get { return fFallecimientoPais; }
            set { SetPropertyValue<int>("FallecimientoPais", ref fFallecimientoPais, value); }
        }
        string fNotas;
        [Size(SizeAttribute.Unlimited)]
        public string Notas
        {
            get { return fNotas; }
            set { SetPropertyValue<string>("Notas", ref fNotas, value); }
        }
        int fDireccionPrimaria;
        public int DireccionPrimaria
        {
            get { return fDireccionPrimaria; }
            set { SetPropertyValue<int>("DireccionPrimaria", ref fDireccionPrimaria, value); }
        }
        byte[] fImagen;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Imagen
        {
            get { return fImagen; }
            set { SetPropertyValue<byte[]>("Imagen", ref fImagen, value); }
        }
        byte[] fImagenFirma;
        [Size(SizeAttribute.Unlimited)]
        public byte[] ImagenFirma
        {
            get { return fImagenFirma; }
            set { SetPropertyValue<byte[]>("ImagenFirma", ref fImagenFirma, value); }
        }
        byte[] fImagenImp;
        [Size(SizeAttribute.Unlimited)]
        public byte[] ImagenImp
        {
            get { return fImagenImp; }
            set { SetPropertyValue<byte[]>("ImagenImp", ref fImagenImp, value); }
        }
        string fCodigoEWS;
        [Size(SizeAttribute.Unlimited)]
        public string CodigoEWS
        {
            get { return fCodigoEWS; }
            set { SetPropertyValue<string>("CodigoEWS", ref fCodigoEWS, value); }
        }
        DateTime fModifFechaEWS;
        public DateTime ModifFechaEWS
        {
            get { return fModifFechaEWS; }
            set { SetPropertyValue<DateTime>("ModifFechaEWS", ref fModifFechaEWS, value); }
        }
        public AgendaPersonas(Session session) : base(session) { }
    }

}
